<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Ong Zhi Rong Jordan">
<meta name="dcterms.date" content="2022-11-24">
<title>Bringing Data to Life - Introduction to Spatial Weights and Application</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../../../styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../media/profile.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Bringing Data to Life</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">About Me</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jordanong09"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#libraries" id="toc-libraries" class="nav-link active" data-scroll-target="#libraries">Libraries</a></li>
  <li>
<a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a>
  <ul class="collapse">
<li><a href="#importing-of-data" id="toc-importing-of-data" class="nav-link" data-scroll-target="#importing-of-data">Importing of data</a></li>
  </ul>
</li>
  <li><a href="#visualisation-of-spatial-data" id="toc-visualisation-of-spatial-data" class="nav-link" data-scroll-target="#visualisation-of-spatial-data">Visualisation of spatial data</a></li>
  <li>
<a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">Computing Contiguity Spatial Weights</a>
  <ul class="collapse">
<li><a href="#computing-queen-contiguity-based-neighbour" id="toc-computing-queen-contiguity-based-neighbour" class="nav-link" data-scroll-target="#computing-queen-contiguity-based-neighbour">Computing (QUEEN) contiguity based neighbour</a></li>
  <li><a href="#computing-rook-contiguity-based-neighbour" id="toc-computing-rook-contiguity-based-neighbour" class="nav-link" data-scroll-target="#computing-rook-contiguity-based-neighbour">Computing (ROOK) contiguity based neighbour</a></li>
  <li><a href="#visualising-the-weights-matrix" id="toc-visualising-the-weights-matrix" class="nav-link" data-scroll-target="#visualising-the-weights-matrix">Visualising the weights matrix</a></li>
  </ul>
</li>
  <li>
<a href="#computing-distance-based-neighbours" id="toc-computing-distance-based-neighbours" class="nav-link" data-scroll-target="#computing-distance-based-neighbours">Computing distance based neighbours</a>
  <ul class="collapse">
<li><a href="#determine-the-cut-off-distance" id="toc-determine-the-cut-off-distance" class="nav-link" data-scroll-target="#determine-the-cut-off-distance">Determine the cut-off distance</a></li>
  <li><a href="#computing-fixed-distance-weight-matrix" id="toc-computing-fixed-distance-weight-matrix" class="nav-link" data-scroll-target="#computing-fixed-distance-weight-matrix">Computing fixed distance weight matrix</a></li>
  <li><a href="#visualising-distance-weight-matrix" id="toc-visualising-distance-weight-matrix" class="nav-link" data-scroll-target="#visualising-distance-weight-matrix">Visualising distance weight matrix</a></li>
  <li><a href="#adaptive-distance-weight-matrix" id="toc-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#adaptive-distance-weight-matrix">Adaptive distance weight matrix</a></li>
  <li><a href="#weights-based-on-inversed-distance-weighting-idw" id="toc-weights-based-on-inversed-distance-weighting-idw" class="nav-link" data-scroll-target="#weights-based-on-inversed-distance-weighting-idw">Weights based on Inversed Distance Weighting (IDW)</a></li>
  </ul>
</li>
  <li>
<a href="#application-of-spatial-weight-matrix" id="toc-application-of-spatial-weight-matrix" class="nav-link" data-scroll-target="#application-of-spatial-weight-matrix">Application of Spatial Weight Matrix</a>
  <ul class="collapse">
<li><a href="#spatial-lag-with-row-standardized-weights" id="toc-spatial-lag-with-row-standardized-weights" class="nav-link" data-scroll-target="#spatial-lag-with-row-standardized-weights">Spatial lag with row-standardized weights</a></li>
  <li><a href="#spatial-lag-as-a-sum-of-neighboring-values" id="toc-spatial-lag-as-a-sum-of-neighboring-values" class="nav-link" data-scroll-target="#spatial-lag-as-a-sum-of-neighboring-values">Spatial lag as a sum of neighboring values</a></li>
  <li><a href="#spatial-window-average" id="toc-spatial-window-average" class="nav-link" data-scroll-target="#spatial-window-average">Spatial window average</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Introduction to Spatial Weights and Application</h1>
<p class="subtitle lead">Computation of spatial weights using R. Understanding the spatial relationships that exist among the features in the dataset.</p>
  <div class="quarto-categories">
    <div class="quarto-category">geospatial</div>
    <div class="quarto-category">sf</div>
    <div class="quarto-category">spdep</div>
    <div class="quarto-category">tmap</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ong Zhi Rong Jordan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 24, 2022</p>
    </div>
  </div>
    
  </div>
  

</header><section id="libraries" class="level2"><h2 class="anchored" data-anchor-id="libraries">Libraries</h2>
<p>For this analysis, we will use the following packages from CRAN.</p>
<ul>
<li>
<a href="https://cloud.r-project.org/web/packages/sf/index.html"><code>sf</code></a> - Support for simple features, a standardized way to encode spatial vector data. Binds to ‘GDAL’ for reading and writing data, to ‘GEOS’ for geometrical operations, and to ‘PROJ’ for projection conversions and datum transformations. Uses by default the ‘s2’ package for spherical geometry operations on ellipsoidal (long/lat) coordinates.</li>
<li>
<a href="https://www.tidyverse.org/packages/"><code>tidyverse</code></a> - Loading the core tidyverse packages which will be used for data wrangling and visualisation.</li>
<li>
<a href="https://cran.r-project.org/web/packages/tmap/index.html"><code>tmap</code></a> - Thematic maps are geographical maps in which spatial data distributions are visualized. This package offers a flexible, layer-based, and easy to use approach to create thematic maps, such as choropleths and bubble maps.</li>
<li>
<a href="https://cran.r-project.org/web/packages/spdep/index.html"><code>spdep</code></a> - A collection of functions to create spatial weights matrix objects from polygon ‘contiguities’, from point patterns by distance and tessellations, for summarizing these objects, and for permitting their use in spatial data analysis, including regional aggregation by minimum spanning tree; a collection of tests for spatial ‘autocorrelation’</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">sf</span>, <span class="va">spdep</span>, <span class="va">tmap</span>, <span class="va">tidyverse</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="data-preparation" class="level2"><h2 class="anchored" data-anchor-id="data-preparation">Data Preparation</h2>
<p>Two dataset will be used for this study:</p>
<ul>
<li>Hunan.shp: A shapefile of the Hunan Province that consist of all the capital</li>
<li>Hunan.csv: A csv file containing multiple attributes of each capital within Hunan</li>
</ul>
<section id="importing-of-data" class="level3"><h3 class="anchored" data-anchor-id="importing-of-data">Importing of data</h3>
<p>We will use the <em>st_read</em> to import the shape file and <em>read_csv</em> to import the aspatial data into the R environment. We will then use a relational join <em>left_join</em> to combine the spatial and aspatial data together.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">hunan</span> <span class="op">&lt;-</span> <span class="fu">st_read</span><span class="op">(</span>dsn <span class="op">=</span> <span class="st">"data/geospatial"</span>, 
                 layer <span class="op">=</span> <span class="st">"Hunan"</span><span class="op">)</span>

<span class="va">hunan2012</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"data/aspatial/Hunan_2012.csv"</span><span class="op">)</span>


<span class="va">hunan</span> <span class="op">&lt;-</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">hunan</span>,<span class="va">hunan2012</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
</section></section><section id="visualisation-of-spatial-data" class="level2"><h2 class="anchored" data-anchor-id="visualisation-of-spatial-data">Visualisation of spatial data</h2>
<p>For the visualisation, we will only be using <code>tmap</code>. We will prepare a basemap anbd a choropleth map to visualise the distribution of GDP per capita among the capital.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">basemap</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_polygons</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_text</span><span class="op">(</span><span class="st">"NAME_3"</span>, size<span class="op">=</span><span class="fl">0.4</span><span class="op">)</span>

<span class="va">gdppc</span> <span class="op">&lt;-</span> <span class="fu">qtm</span><span class="op">(</span><span class="va">hunan</span>, <span class="st">"GDPPC"</span><span class="op">)</span>

<span class="fu">tmap_arrange</span><span class="op">(</span><span class="va">basemap</span>, <span class="va">gdppc</span>, asp<span class="op">=</span><span class="fl">1</span>, ncol<span class="op">=</span><span class="fl">2</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="tmap01.png" class="img-fluid figure-img" width="1050"></p>
<p></p><figcaption class="figure-caption">base map and choropleth map</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="computing-contiguity-spatial-weights" class="level2"><h2 class="anchored" data-anchor-id="computing-contiguity-spatial-weights">Computing Contiguity Spatial Weights</h2>
<p>Contiguity means that two spatial units share a common border of non-zero length. There are multiple criterion of contiguity such as:</p>
<ul>
<li>
<strong>Rook</strong>: When only common sides of the polygons are considered to define the neighbor relation (common vertices are ignored).</li>
<li>
<strong>Queen</strong>: The difference between the rook and queen criterion to determine neighbors is that the latter also includes common vertices.</li>
<li>
<strong>Bishop</strong>: Is based on the existence of common vertices between two spatial units.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="contiguity.png" class="img-fluid figure-img" width="293"></p>
<p></p><figcaption class="figure-caption">Contiguity Weights</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Except in the simplest of circumstances, visual examination or manual calculation cannot be used to create the spatial weights from the geometry of the data. It is necessary to utilize explicit spatial data structures to deal with the placement and layout of the polygons in order to determine whether two polygons are contiguous.</p>
<p>We will use the <a href="https://www.rdocumentation.org/packages/spdep/versions/1.2-7/topics/poly2nb"><code>poly2nb</code></a> function to construct neighbours list based on the regions with contiguous boundaries. Based on the documentation, user will be able to pass a <code>queen</code> argument that takes in True or False. The argument the default is set to TRUE, that is, if you don’t specify queen = FALSE this function will return a list of first order neighbours using the Queen criteria.</p>
<section id="computing-queen-contiguity-based-neighbour" class="level3"><h3 class="anchored" data-anchor-id="computing-queen-contiguity-based-neighbour">Computing (QUEEN) contiguity based neighbour</h3>
<p>The code chunk below is used to compute Queen contiguity weight matrix.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_q</span> <span class="op">&lt;-</span> <span class="fu">poly2nb</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wm_q</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 
Link number distribution:

 1  2  3  4  5  6  7  8  9 11 
 2  2 12 16 24 14 11  4  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 11 links</code></pre>
</div>
</div>
<p>based on the summary report above,the report shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbours.</p>
<p>For each polygon in our polygon object, wm_q lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, type:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_q</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4 57 85</code></pre>
</div>
</div>
<p>Polygon 1 has 5 neighbors. The numbers represent the polygon IDs as stored in hunan SpatialPolygonsDataFrame class.</p>
<p>To reveal the county names of the five neighboring polygons, the code chunk will be used:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">hunan</span><span class="op">$</span><span class="va">NAME_3</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span>,<span class="fl">57</span>,<span class="fl">85</span><span class="op">)</span><span class="op">]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hanshou" "Jinshi"  "Li"      "Nan"     "Taoyuan"</code></pre>
</div>
</div>
<p>We can retrieve the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">hunan</span><span class="op">$</span><span class="va">GDPPC</span><span class="op">[</span><span class="va">wm_q</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20981 34592 24473 21311 22879</code></pre>
</div>
</div>
<p>The printed output above shows that the GDPPC of the five nearest neighbours based on Queen’s method are 20981, 34592, 24473, 21311 and 22879 respectively.</p>
<p>You can display the complete weight matrix by using str().</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">wm_q</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 88
 $ : int [1:5] 2 3 4 57 85
 $ : int [1:5] 1 57 58 78 85
 $ : int [1:4] 1 4 5 85
 $ : int [1:4] 1 3 5 6
 $ : int [1:4] 3 4 6 85
 $ : int [1:5] 4 5 69 75 85
 $ : int [1:4] 67 71 74 84
 $ : int [1:7] 9 46 47 56 78 80 86
 $ : int [1:6] 8 66 68 78 84 86
 $ : int [1:8] 16 17 19 20 22 70 72 73
 $ : int [1:3] 14 17 72
 $ : int [1:5] 13 60 61 63 83
 $ : int [1:4] 12 15 60 83
 $ : int [1:3] 11 15 17
 $ : int [1:4] 13 14 17 83
 $ : int [1:5] 10 17 22 72 83
 $ : int [1:7] 10 11 14 15 16 72 83
 $ : int [1:5] 20 22 23 77 83
 $ : int [1:6] 10 20 21 73 74 86
 $ : int [1:7] 10 18 19 21 22 23 82
 $ : int [1:5] 19 20 35 82 86
 $ : int [1:5] 10 16 18 20 83
 $ : int [1:7] 18 20 38 41 77 79 82
 $ : int [1:5] 25 28 31 32 54
 $ : int [1:5] 24 28 31 33 81
 $ : int [1:4] 27 33 42 81
 $ : int [1:3] 26 29 42
 $ : int [1:5] 24 25 33 49 54
 $ : int [1:3] 27 37 42
 $ : int 33
 $ : int [1:8] 24 25 32 36 39 40 56 81
 $ : int [1:8] 24 31 50 54 55 56 75 85
 $ : int [1:5] 25 26 28 30 81
 $ : int [1:3] 36 45 80
 $ : int [1:6] 21 41 47 80 82 86
 $ : int [1:6] 31 34 40 45 56 80
 $ : int [1:4] 29 42 43 44
 $ : int [1:4] 23 44 77 79
 $ : int [1:5] 31 40 42 43 81
 $ : int [1:6] 31 36 39 43 45 79
 $ : int [1:6] 23 35 45 79 80 82
 $ : int [1:7] 26 27 29 37 39 43 81
 $ : int [1:6] 37 39 40 42 44 79
 $ : int [1:4] 37 38 43 79
 $ : int [1:6] 34 36 40 41 79 80
 $ : int [1:3] 8 47 86
 $ : int [1:5] 8 35 46 80 86
 $ : int [1:5] 50 51 52 53 55
 $ : int [1:4] 28 51 52 54
 $ : int [1:5] 32 48 52 54 55
 $ : int [1:3] 48 49 52
 $ : int [1:5] 48 49 50 51 54
 $ : int [1:3] 48 55 75
 $ : int [1:6] 24 28 32 49 50 52
 $ : int [1:5] 32 48 50 53 75
 $ : int [1:7] 8 31 32 36 78 80 85
 $ : int [1:6] 1 2 58 64 76 85
 $ : int [1:5] 2 57 68 76 78
 $ : int [1:4] 60 61 87 88
 $ : int [1:4] 12 13 59 61
 $ : int [1:7] 12 59 60 62 63 77 87
 $ : int [1:3] 61 77 87
 $ : int [1:4] 12 61 77 83
 $ : int [1:2] 57 76
 $ : int 76
 $ : int [1:5] 9 67 68 76 84
 $ : int [1:4] 7 66 76 84
 $ : int [1:5] 9 58 66 76 78
 $ : int [1:3] 6 75 85
 $ : int [1:3] 10 72 73
 $ : int [1:3] 7 73 74
 $ : int [1:5] 10 11 16 17 70
 $ : int [1:5] 10 19 70 71 74
 $ : int [1:6] 7 19 71 73 84 86
 $ : int [1:6] 6 32 53 55 69 85
 $ : int [1:7] 57 58 64 65 66 67 68
 $ : int [1:7] 18 23 38 61 62 63 83
 $ : int [1:7] 2 8 9 56 58 68 85
 $ : int [1:7] 23 38 40 41 43 44 45
 $ : int [1:8] 8 34 35 36 41 45 47 56
 $ : int [1:6] 25 26 31 33 39 42
 $ : int [1:5] 20 21 23 35 41
 $ : int [1:9] 12 13 15 16 17 18 22 63 77
 $ : int [1:6] 7 9 66 67 74 86
 $ : int [1:11] 1 2 3 5 6 32 56 57 69 75 ...
 $ : int [1:9] 8 9 19 21 35 46 47 74 84
 $ : int [1:4] 59 61 62 88
 $ : int [1:2] 59 87
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:88] "1" "2" "3" "4" ...
 - attr(*, "call")= language poly2nb(pl = hunan)
 - attr(*, "type")= chr "queen"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
</section><section id="computing-rook-contiguity-based-neighbour" class="level3"><h3 class="anchored" data-anchor-id="computing-rook-contiguity-based-neighbour">Computing (ROOK) contiguity based neighbour</h3>
<p>The code chunk below is used to compute Rook contiguity weight matrix.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_r</span> <span class="op">&lt;-</span> <span class="fu">poly2nb</span><span class="op">(</span><span class="va">hunan</span>, queen<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wm_r</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 440 
Percentage nonzero weights: 5.681818 
Average number of links: 5 
Link number distribution:

 1  2  3  4  5  6  7  8  9 10 
 2  2 12 20 21 14 11  3  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 10 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 88 area units in Hunan. The most connect area unit has 10 neighbours. There are two area units with only one heighbours.</p>
</section><section id="visualising-the-weights-matrix" class="level3"><h3 class="anchored" data-anchor-id="visualising-the-weights-matrix">Visualising the weights matrix</h3>
<p>A connectivity graph takes a point and displays a line to each neighboring point. We are working with polygons at the moment, so we will need to get points in order to make our connectivity graphs. The most typically method for this will be polygon centroids. To retrieve the centroid of each area, we will use the <code>st_centroid</code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">coords</span> <span class="op">&lt;-</span> <span class="fu">st_centroid</span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="plotting-queen-and-rook-contiguity-based-neighbours-map" class="level4"><h4 class="anchored" data-anchor-id="plotting-queen-and-rook-contiguity-based-neighbours-map">Plotting Queen and Rook contiguity based neighbours map</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span>, border<span class="op">=</span><span class="st">"grey"</span>, main <span class="op">=</span> <span class="st">"Queen Contiguity"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">wm_q</span>, <span class="va">coords</span>,pch <span class="op">=</span> <span class="fl">19</span>, cex <span class="op">=</span> <span class="fl">0.6</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, col<span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">st_geometry</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span>, border<span class="op">=</span><span class="st">"grey"</span>, main <span class="op">=</span> <span class="st">"Rook Contiguity"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">wm_r</span>, <span class="va">coords</span>,pch <span class="op">=</span> <span class="fl">19</span>, cex <span class="op">=</span> <span class="fl">0.6</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, col<span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section></section><section id="computing-distance-based-neighbours" class="level2"><h2 class="anchored" data-anchor-id="computing-distance-based-neighbours">Computing distance based neighbours</h2>
<p>In this section, you will learn how to derive distance-based weight matrices by using <a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html"><code>dnearneigh()</code></a> of <strong>spdep</strong> package. The function identifies neighbours of region points by Euclidean distance in the metric of the points between lower (greater than or equal to and upper (less than or equal to) bounds.</p>
<section id="determine-the-cut-off-distance" class="level3"><h3 class="anchored" data-anchor-id="determine-the-cut-off-distance">Determine the cut-off distance</h3>
<p>Firstly, we need to determine the upper limit for distance band by using the steps below:</p>
<ul>
<li><p>Return a matrix with the indices of points belonging to the set of the k nearest neighbours of each other by using <a href="https://r-spatial.github.io/spdep/reference/knearneigh.html"><em>knearneigh()</em></a> of <strong>spdep</strong>.</p></li>
<li><p>Convert the knn object returned by <em>knearneigh()</em> into a neighbours list of class nb with a list of integer vectors containing neighbour region number ids by using <a href="https://r-spatial.github.io/spdep/reference/knn2nb.html"><em>knn2nb()</em></a>.</p></li>
<li><p>Return the length of neighbour relationship edges by using <a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a> of <strong>spdep</strong>. The function returns in the units of the coordinates if the coordinates are projected, in km otherwise.</p></li>
<li><p>Remove the list structure of the returned object by using <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist"><strong>unlist()</strong></a>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">k1</span> <span class="op">&lt;-</span> <span class="fu">knn2nb</span><span class="op">(</span><span class="fu">knearneigh</span><span class="op">(</span><span class="va">coords</span><span class="op">)</span><span class="op">)</span>
<span class="va">k1dists</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unlist.html">unlist</a></span><span class="op">(</span><span class="fu">nbdists</span><span class="op">(</span><span class="va">k1</span>, <span class="va">coords</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">k1dists</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  24.80   32.53   38.06   38.91   44.66   58.25 </code></pre>
</div>
</div>
<p>The summary report shows that the largest first nearest neighbour distance is 58.25 km, so using this as the upper threshold gives certainty that all units will have at least one neighbour.</p>
</section><section id="computing-fixed-distance-weight-matrix" class="level3"><h3 class="anchored" data-anchor-id="computing-fixed-distance-weight-matrix">Computing fixed distance weight matrix</h3>
<p>Now, we will compute the distance weight matrix by using <em>dnearneigh()</em> as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_d62</span> <span class="op">&lt;-</span> <span class="fu">dnearneigh</span><span class="op">(</span><span class="va">coords</span>, <span class="fl">0</span>, <span class="fl">59</span><span class="op">)</span>
<span class="va">wm_d62</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 298 
Percentage nonzero weights: 3.84814 
Average number of links: 3.386364 </code></pre>
</div>
</div>
<p>The report shows that on average, every area should have at least 3 neighbours (links).</p>
<p>To display the structure of the weight matrix is to combine <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table"><em>table()</em></a> and <a href="https://r-spatial.github.io/spdep/reference/card.html"><em>card()</em></a> of spdep.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">County</span>, <span class="fu">card</span><span class="op">(</span><span class="va">wm_d62</span><span class="op">)</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                1 2 3 4 5 6
  Anhua         1 0 0 0 0 0
  Anren         0 0 0 1 0 0
  Anxiang       0 0 0 0 1 0
  Baojing       0 0 0 1 0 0
  Chaling       0 0 1 0 0 0
  Changning     0 0 1 0 0 0
  Changsha      0 0 0 1 0 0
  Chengbu       1 0 0 0 0 0
  Chenxi        0 0 0 1 0 0
  Cili          1 0 0 0 0 0
  Dao           0 0 1 0 0 0
  Dongan        0 0 1 0 0 0
  Dongkou       0 0 0 1 0 0
  Fenghuang     0 0 0 1 0 0
  Guidong       0 0 1 0 0 0
  Guiyang       0 0 1 0 0 0
  Guzhang       0 0 0 0 0 1
  Hanshou       0 0 0 1 0 0
  Hengdong      0 0 1 0 0 0
  Hengnan       0 0 0 0 1 0
  Hengshan      0 0 0 0 0 1
  Hengyang      0 0 0 0 1 0
  Hongjiang     0 0 0 1 0 0
  Huarong       0 0 1 0 0 0
  Huayuan       0 0 0 1 0 0
  Huitong       0 0 0 1 0 0
  Jiahe         0 0 0 0 1 0
  Jianghua      0 1 0 0 0 0
  Jiangyong     0 1 0 0 0 0
  Jingzhou      0 1 0 0 0 0
  Jinshi        0 0 0 1 0 0
  Jishou        0 0 0 0 0 1
  Lanshan       0 0 0 1 0 0
  Leiyang       0 0 0 1 0 0
  Lengshuijiang 0 0 1 0 0 0
  Li            0 0 1 0 0 0
  Lianyuan      0 0 0 1 0 0
  Liling        0 1 0 0 0 0
  Linli         0 0 1 0 0 0
  Linwu         0 0 0 1 0 0
  Linxiang      1 0 0 0 0 0
  Liuyang       0 1 0 0 0 0
  Longhui       0 0 1 0 0 0
  Longshan      1 0 0 0 0 0
  Luxi          0 0 0 0 1 0
  Mayang        0 0 0 0 0 1
  Miluo         0 0 0 0 1 0
  Nan           0 0 0 0 1 0
  Ningxiang     0 0 0 1 0 0
  Ningyuan      0 0 0 0 1 0
  Pingjiang     0 1 0 0 0 0
  Qidong        0 0 1 0 0 0
  Qiyang        0 0 1 0 0 0
  Rucheng       0 1 0 0 0 0
  Sangzhi       1 0 0 0 0 0
  Shaodong      0 0 0 0 1 0
  Shaoshan      0 0 0 1 0 0
  Shaoyang      0 0 0 1 0 0
  Shimen        1 0 0 0 0 0
  Shuangfeng    0 0 0 0 1 0
  Shuangpai     0 0 0 1 0 0
  Suining       0 0 0 1 0 0
  Taojiang      0 1 0 0 0 0
  Taoyuan       1 0 0 0 0 0
  Tongdao       1 0 0 0 0 0
  Wangcheng     0 0 0 1 0 0
  Wugang        0 0 1 0 0 0
  Xiangtan      0 0 0 1 0 0
  Xiangxiang    0 0 0 0 1 0
  Xiangyin      0 0 0 1 0 0
  Xinhua        0 0 0 1 0 0
  Xinhuang      1 0 0 0 0 0
  Xinning       0 1 0 0 0 0
  Xinshao       0 0 0 0 0 1
  Xintian       0 0 0 0 1 0
  Xupu          0 1 0 0 0 0
  Yanling       0 0 1 0 0 0
  Yizhang       1 0 0 0 0 0
  Yongshun      0 0 0 1 0 0
  Yongxing      0 0 1 0 0 0
  You           0 0 1 0 0 0
  Yuanjiang     0 0 0 0 1 0
  Yuanling      1 0 0 0 0 0
  Yueyang       0 1 0 0 0 0
  Zhijiang      0 0 0 0 1 0
  Zhongfang     0 0 0 1 0 0
  Zhuzhou       0 0 1 0 0 0
  Zixing        0 0 1 0 0 0</code></pre>
</div>
</div>
</section><section id="visualising-distance-weight-matrix" class="level3"><h3 class="anchored" data-anchor-id="visualising-distance-weight-matrix">Visualising distance weight matrix</h3>
<p>The left graph with the red lines show the links of 1st nearest neighbours and the right graph with the black lines show the links of neighbours within the cut-off distance of 59km.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">geometry</span>, border<span class="op">=</span><span class="st">"lightgrey"</span>, main<span class="op">=</span><span class="st">"1st nearest neighbours"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">k1</span>, <span class="va">coords</span>, add<span class="op">=</span><span class="cn">TRUE</span>, col<span class="op">=</span><span class="st">"red"</span>, length<span class="op">=</span><span class="fl">0.08</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">geometry</span>, border<span class="op">=</span><span class="st">"lightgrey"</span>, main<span class="op">=</span><span class="st">"Distance link"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">wm_d62</span>, <span class="va">coords</span>, add<span class="op">=</span><span class="cn">TRUE</span>, pch <span class="op">=</span> <span class="fl">19</span>, cex <span class="op">=</span> <span class="fl">0.6</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section><section id="adaptive-distance-weight-matrix" class="level3"><h3 class="anchored" data-anchor-id="adaptive-distance-weight-matrix">Adaptive distance weight matrix</h3>
<p>Other than using distance as a criteria to decide the neighbours, it is possible to control the numbers of neighbours directly using k-nearest neighbours, either accepting asymmetric neighbours or imposing symmetry as shown in the code chunk below:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">knn6</span> <span class="op">&lt;-</span> <span class="fu">knn2nb</span><span class="op">(</span><span class="fu">knearneigh</span><span class="op">(</span><span class="va">coords</span>, k<span class="op">=</span><span class="fl">6</span><span class="op">)</span><span class="op">)</span> <span class="co">#k refers to the number of neighbours per area</span>
<span class="va">knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 528 
Percentage nonzero weights: 6.818182 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<section id="plotting-adaptive-distance-weight" class="level4"><h4 class="anchored" data-anchor-id="plotting-adaptive-distance-weight">Plotting adaptive distance weight</h4>
<p>We can plot the adaptive distance weight matrix using the code chunk below:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">geometry</span>, border<span class="op">=</span><span class="st">"lightgrey"</span>, main <span class="op">=</span> <span class="st">"Adaptive Distance Weight"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">knn6</span>, <span class="va">coords</span>, pch <span class="op">=</span> <span class="fl">19</span>, cex <span class="op">=</span> <span class="fl">0.6</span>, add <span class="op">=</span> <span class="cn">TRUE</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section></section><section id="weights-based-on-inversed-distance-weighting-idw" class="level3"><h3 class="anchored" data-anchor-id="weights-based-on-inversed-distance-weighting-idw">Weights based on Inversed Distance Weighting (IDW)</h3>
<p>In this section, you will learn how to derive a spatial weight matrix based on Inversed Distance method.</p>
<p>First, we will compute the distances between areas by using <em>nbdists()</em> of <strong>spdep</strong>.</p>
<p>We will use the [<code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code>] (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/lapply) to apply the inverse function through the list.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">dist</span> <span class="op">&lt;-</span> <span class="fu">nbdists</span><span class="op">(</span><span class="va">wm_q</span>, <span class="va">coords</span>, longlat <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">ids</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">dist</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fl">1</span><span class="op">/</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">ids</span>,<span class="fl">5</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 1.694446 3.805533 1.847048 2.867007 1.166097

[[2]]
[1] 1.694446 1.832614 1.889267 2.537233 1.681209

[[3]]
[1] 3.805533 3.007305 3.588446 1.468997

[[4]]
[1] 1.847048 3.007305 3.731278 1.490622

[[5]]
[1] 3.588446 3.731278 1.526472 1.775459</code></pre>
</div>
</div>
<p>Next, we will use the <a href="https://www.rdocumentation.org/packages/spdep/versions/1.2-7/topics/nb2listw"><code>nb2listw</code></a> to apply the weights list with values given by the coding scheme style chosen. There are multiple style to choose from:</p>
<ul>
<li>B (Basic Binary Coding)</li>
<li>W (Row Standardised) - sums over all links to n</li>
<li>C (Globally Standardised) - sums over all links to n</li>
<li>U (Globally Standardised / No of neighbours) - sums over all links to unity</li>
<li>S (Variance-Stabilizing Coding Scheme) - sums over all links to n</li>
<li>minmax - divides the weights by the minimum of the maximum row sums and maximum column sums of the input weights</li>
</ul>
<p>For the simplifed analysis, we will use the W (Row Standardised).</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">rswm_q</span> <span class="op">&lt;-</span> <span class="fu">nb2listw</span><span class="op">(</span><span class="va">wm_q</span>, style<span class="op">=</span><span class="st">"W"</span>, zero.policy <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">rswm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 88 7744 88 37.86334 365.9147</code></pre>
</div>
</div>
<p>From the earlier example, we know that the first Id has 5 neighbours. We take a look at the weight distribution of these 5 neighours. Since we are using Row Standardised, they should be equal.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">rswm_q</span><span class="op">$</span><span class="va">weights</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.2 0.2 0.2 0.2 0.2</code></pre>
</div>
</div>
<p>Each neighbor is assigned a 0.2 of the total weight. This means that when R computes the average neighboring income values, each neighbor’s income will be multiplied by 0.2 before being tallied.</p>
</section></section><section id="application-of-spatial-weight-matrix" class="level2"><h2 class="anchored" data-anchor-id="application-of-spatial-weight-matrix">Application of Spatial Weight Matrix</h2>
<p>In this section, you will learn how to create four different spatial lagged variables, they are:</p>
<ul>
<li>spatial lag with row-standardized weights</li>
<li>spatial lag as a sum of neighbouring values</li>
<li>spatial window average</li>
<li>spatial window sum</li>
</ul>
<section id="spatial-lag-with-row-standardized-weights" class="level3"><h3 class="anchored" data-anchor-id="spatial-lag-with-row-standardized-weights">Spatial lag with row-standardized weights</h3>
<p>Firstly, we’ll compute the average neighbor GDPPC value for each polygon using the <a href="https://www.rdocumentation.org/packages/spdep/versions/1.1-3/topics/lag.listw"><code>lag.listw()</code></a> that can compute the lag of a vector. These values are often referred to as spatially lagged values.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">GDPPC.lag</span> <span class="op">&lt;-</span> <span class="fu">lag.listw</span><span class="op">(</span><span class="va">rswm_q</span>, <span class="va">hunan</span><span class="op">$</span><span class="va">GDPPC</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">GDPPC.lag</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24847.20 22724.80 24143.25 27737.50 27270.25 21248.80</code></pre>
</div>
</div>
<p>In the previous section, we retrieved the GDPPC of the neighbours of the first area by using the following code chunk:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">hunan</span><span class="op">$</span><span class="va">GDPPC</span><span class="op">[</span><span class="va">wm_q</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20981 34592 24473 21311 22879</code></pre>
</div>
</div>
<p>From this, we can understand that the spatial lag with row-standardized weights is actually the average GDPPC of its neighbours.</p>
<p><span class="math display">\[(20981+34592+24473+21311+22879/5 = 24847.20)\]</span></p>
<p>We will now append these lagged values to our <code>Hunan</code> data frame.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">lag.df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">NAME_3</span>,<span class="va">GDPPC.lag</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">lag.df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"NAME_3"</span>, <span class="st">"lag GDPPC"</span><span class="op">)</span>
<span class="va">hunan</span> <span class="op">&lt;-</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">hunan</span>,<span class="va">lag.df</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will plot both the GDPPC and spatial lag GDPPC for comparison using the code chunk below.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC without lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>
  
<span class="va">lag_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>
<span class="fu">tmap_arrange</span><span class="op">(</span><span class="va">gdppc</span>, <span class="va">lag_gdppc</span>, asp<span class="op">=</span><span class="fl">1</span>, ncol<span class="op">=</span><span class="fl">2</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="tmap02.png" class="img-fluid figure-img" width="1050"></p>
<p></p><figcaption class="figure-caption">GDPPC vs lag GDPPC</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="spatial-lag-as-a-sum-of-neighboring-values" class="level3"><h3 class="anchored" data-anchor-id="spatial-lag-as-a-sum-of-neighboring-values">Spatial lag as a sum of neighboring values</h3>
<p>We can calculate spatial lag as a sum of neighboring values by assigning binary weights. This requires us to go back to our neighbors list, then apply a function that will assign binary weights, then we use glist = in the nb2listw function to explicitly assign these weights.</p>
<p>We start by applying a function that will assign a value of 1 per each neighbor. This is done with lapply, which we have been using to manipulate the neighbors structure throughout the past notebooks. Basically it applies a function across each value in the neighbors structure.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">b_weights</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">wm_q</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fl">0</span><span class="op">*</span><span class="va">x</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span>

<span class="va">b_weights2</span> <span class="op">&lt;-</span> <span class="fu">nb2listw</span><span class="op">(</span><span class="va">wm_q</span>, 
                       glist <span class="op">=</span> <span class="va">b_weights</span>, 
                       style <span class="op">=</span> <span class="st">"B"</span><span class="op">)</span>
<span class="va">b_weights2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: B 
Weights constants summary:
   n   nn  S0  S1    S2
B 88 7744 448 896 10224</code></pre>
</div>
</div>
<p>With the proper weights assigned, we can use lag.listw to compute a lag variable from our weight and GDPPC.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">lag_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">NAME_3</span>, <span class="fu">lag.listw</span><span class="op">(</span><span class="va">b_weights2</span>, <span class="va">hunan</span><span class="op">$</span><span class="va">GDPPC</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">lag_df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"NAME_3"</span>, <span class="st">"lag_sum GDPPC"</span><span class="op">)</span>
<span class="va">hunan</span> <span class="op">&lt;-</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">hunan</span>, <span class="va">lag_df</span><span class="op">)</span>

<span class="va">lag_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          NAME_3 lag_sum GDPPC
1        Anxiang        124236
2        Hanshou        113624
3         Jinshi         96573
4             Li        110950
5          Linli        109081
6         Shimen        106244
7        Liuyang        174988
8      Ningxiang        235079
9      Wangcheng        273907
10         Anren        256221
11       Guidong         98013
12         Jiahe        104050
13         Linwu        102846
14       Rucheng         92017
15       Yizhang        133831
16      Yongxing        158446
17        Zixing        141883
18     Changning        119508
19      Hengdong        150757
20       Hengnan        153324
21      Hengshan        113593
22       Leiyang        129594
23        Qidong        142149
24        Chenxi        100119
25     Zhongfang         82884
26       Huitong         74668
27      Jingzhou         43184
28        Mayang         99244
29       Tongdao         46549
30      Xinhuang         20518
31          Xupu        140576
32      Yuanling        121601
33      Zhijiang         92069
34 Lengshuijiang         43258
35    Shuangfeng        144567
36        Xinhua        132119
37       Chengbu         51694
38        Dongan         59024
39       Dongkou         69349
40       Longhui         73780
41      Shaodong         94651
42       Suining        100680
43        Wugang         69398
44       Xinning         52798
45       Xinshao        140472
46      Shaoshan        118623
47    Xiangxiang        180933
48       Baojing         82798
49     Fenghuang         83090
50       Guzhang         97356
51       Huayuan         59482
52        Jishou         77334
53      Longshan         38777
54          Luxi        111463
55      Yongshun         74715
56         Anhua        174391
57           Nan        150558
58     Yuanjiang        122144
59      Jianghua         68012
60       Lanshan         84575
61      Ningyuan        143045
62     Shuangpai         51394
63       Xintian         98279
64       Huarong         47671
65      Linxiang         26360
66         Miluo        236917
67     Pingjiang        220631
68      Xiangyin        185290
69          Cili         64640
70       Chaling         70046
71        Liling        126971
72       Yanling        144693
73           You        129404
74       Zhuzhou        284074
75       Sangzhi        112268
76       Yueyang        203611
77        Qiyang        145238
78      Taojiang        251536
79      Shaoyang        108078
80      Lianyuan        238300
81     Hongjiang        108870
82      Hengyang        108085
83       Guiyang        262835
84      Changsha        248182
85       Taoyuan        244850
86      Xiangtan        404456
87           Dao         67608
88     Jiangyong         33860</code></pre>
</div>
</div>
<p>From the above data table and the GDPPC from the previous section, we know that the lagged sum is the addition of all the GDPPC of its neighbours.</p>
<p><span class="math display">\[(20981+34592+24473+21311+22879 = 124236)\]</span></p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC without lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>
  
<span class="va">lag_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>

<span class="va">lag_sum_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag_sum GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged sum values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>

<span class="fu">tmap_arrange</span><span class="op">(</span><span class="va">gdppc</span>, <span class="va">lag_gdppc</span>, <span class="va">lag_sum_gdppc</span>, asp<span class="op">=</span><span class="fl">1</span>, ncol<span class="op">=</span><span class="fl">3</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="tmap03.png" class="img-fluid figure-img" width="1800"></p>
<p></p><figcaption class="figure-caption">GDPPC vs lag GDPPC vs lag sum GDPPC</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="spatial-window-average" class="level3"><h3 class="anchored" data-anchor-id="spatial-window-average">Spatial window average</h3>
<p>The spatial window average uses row-standardized weights and includes the diagonal element. (region itself) We will use the <a href="https://r-spatial.github.io/spdep/reference/include.self.html"><code>include.self()</code></a>.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_q_self</span> <span class="op">&lt;-</span> <span class="fu">include.self</span><span class="op">(</span><span class="va">wm_q</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will now obtain the weight and retrieve the new spatial window average and combine it with our exisiting <code>Hunan</code> dataframe.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">wm_q_self</span> <span class="op">&lt;-</span> <span class="fu">nb2listw</span><span class="op">(</span><span class="va">wm_q_self</span><span class="op">)</span>
<span class="va">lag_w_avg_gpdpc</span> <span class="op">&lt;-</span> <span class="fu">lag.listw</span><span class="op">(</span><span class="va">wm_q_self</span>, 
                             <span class="va">hunan</span><span class="op">$</span><span class="va">GDPPC</span><span class="op">)</span>

<span class="va">lag_w_avg_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">hunan</span><span class="op">$</span><span class="va">NAME_3</span>, <span class="va">lag_w_avg_gpdpc</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">lag_w_avg_df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"NAME_3"</span>, <span class="st">"lag_window_avg GDPPC"</span><span class="op">)</span>

<span class="va">hunan</span> <span class="op">&lt;-</span> <span class="fu">left_join</span><span class="op">(</span><span class="va">hunan</span>, <span class="va">lag_w_avg_df</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC without lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>
  
<span class="va">lag_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>

<span class="va">lag_sum_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag_sum GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged sum values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>

<span class="va">lag_sum_avg_gdppc</span> <span class="op">&lt;-</span> <span class="fu">tm_shape</span><span class="op">(</span><span class="va">hunan</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_fill</span><span class="op">(</span><span class="st">"lag_window_avg GDPPC"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_borders</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">tm_layout</span><span class="op">(</span>main.title <span class="op">=</span> <span class="st">"GDPPC with lagged sum average values"</span>, main.title.size <span class="op">=</span> <span class="fl">0.7</span>, legend.text.size <span class="op">=</span> <span class="fl">0.4</span>,
            main.title.fontface <span class="op">=</span> <span class="st">"bold"</span>,main.title.position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span>

<span class="fu">tmap_arrange</span><span class="op">(</span><span class="va">gdppc</span>, <span class="va">lag_gdppc</span>, <span class="va">lag_sum_gdppc</span>, <span class="va">lag_sum_avg_gdppc</span>, asp<span class="op">=</span><span class="fl">1</span>, ncol<span class="op">=</span><span class="fl">2</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="tmap04.png" class="img-fluid figure-img" width="1800"></p>
<p></p><figcaption class="figure-caption">GDPPC vs lag GDPPC vs lag sum GDPPC vs lag sum avg GDPPC</figcaption><p></p>
</figure>
</div>
</div>
</div>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><script src="https://giscus.app/client.js" data-repo="jordanong09/ISSS624_Geospatial" data-repo-id="R_kgDOIciwvg" data-category="General" data-category-id="DIC_kwDOIciwvs4CSm3Z" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>